"""Macro domain models: economic events, evidence classifications, and lock states."""

from decimal import Decimal
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class EventImpact(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class EventClassification(StrEnum):
    FACT = "FACT"
    EXPECTATION = "EXPECTATION"
    ANALYSIS = "ANALYSIS"
    AI_INTERPRETATION = "AI_INTERPRETATION"


class NewsLockState(StrEnum):
    CLEAR = "CLEAR"
    NEWS_LOCK = "NEWS_LOCK"
    POST_NEWS_REASSESSMENT = "POST_NEWS_REASSESSMENT"


class EconomicEvent(BaseModel):
    """Immutable representation of a scheduled economic calendar event."""

    model_config = ConfigDict(frozen=True)

    event_id: str
    name: str
    impact: EventImpact
    timestamp_ms: int
    source: str
    actual_value: str | None = None
    forecast_value: str | None = None
    previous_value: str | None = None


class MacroAssessment(BaseModel):
    """Immutable advisory assessment generated by macro intelligence."""

    model_config = ConfigDict(frozen=True)

    assessment_id: str
    timestamp_ms: int
    classification: EventClassification
    gold_catalyst_bias: str
    confidence_score: Decimal = Field(ge=Decimal("0.0"), le=Decimal("1.0"))
    summary: str
    reasoning: str
    source: str
